### ISSUE TITLE
error: command 'swig.exe' failed: None

### ISSUE THREAD

**Issue by kakaon1** [wikibook/mpytc#1]
해당 파일로 설치를 진행하면 문제가 생겨서.

에러의 문제인 Autotorch 를 지우고 설치를 하면...

Jupyter lab에서 DLL을 찾을 수 없다는 에러가 뜹니다.

확인 후 조취부탁드립니다.

**Comment by ychoi-kr** [comment]
어떤 DLL을 찾을 수 없다고 나오는지 에러 메시지를 복사해서 댓글에 써주시겠어요?

**Comment by kakaon1** [comment]
conda env create --file environment.yaml

일단 명령어는 이걸로 했구요...

그냥 설치하면..

================================================================================

Collecting tenacity>=6.2.0
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Building wheels for collected packages: pycocotools, torchviz, gym, hpbandster, gast, pyrfr, smac, pynisher, future
  Building wheel for pycocotools (setup.py): started
  Building wheel for pycocotools (setup.py): finished with status 'done'
  Created wheel for pycocotools: filename=pycocotools-2.0-cp37-cp37m-win_amd64.whl size=76610 sha256=b3acf76f6f9304ec650a2621d6adf017e14cd5cdee5be0dc43a3999a5c55769e
  Stored in directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-ephem-wheel-cache-8au8by6o\wheels\6b\c6\c5\cb6da4cb793a6cb1ab91f6578d76c42686422127eb4dbcea94
  Building wheel for torchviz (setup.py): started
  Building wheel for torchviz (setup.py): finished with status 'done'
  Created wheel for torchviz: filename=torchviz-0.0.2-py3-none-any.whl size=4137 sha256=cb63b38e68ed6ee04c9f74859ee54ab01fba27de2ac9999b3ddf62f91e39c8ec
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\18\0c\ac\81bacd5a53085ac633beb52c80c08152db65a81e93b15b392d
  Building wheel for gym (setup.py): started
  Building wheel for gym (setup.py): finished with status 'done'
  Created wheel for gym: filename=gym-0.19.0-py3-none-any.whl size=1663096 sha256=f177e7c197993e1c540c5572ca340e8c9cae0ca91ef729447fea0afa7c4f850d
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\47\a0\57\3216e63a8d898a818bd2a41f0c8ad9f23cd90a9bb7f97fdf53
  Building wheel for hpbandster (setup.py): started
  Building wheel for hpbandster (setup.py): finished with status 'done'
  Created wheel for hpbandster: filename=hpbandster-0.7.4-py3-none-any.whl size=90205 sha256=58b85d6556171258aa5ede423dceb40dbe2e1ecd53d629fd7ec5451f8a02a9ed
  Stored in directory: C:\Users\ADMINI~1\AppData\Local\Temp\pip-ephem-wheel-cache-8au8by6o\wheels\cb\66\a2\0d58f0cf5fae822e1f5657e712760143ac8ac6be406d43ad65
  Building wheel for gast (setup.py): started
  Building wheel for gast (setup.py): finished with status 'done'
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7549 sha256=1ba7a67f7b9d0b8b21d39f841180452d8343a965644201f02999cc5fda8bb739
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\cf\87\6f\3f34218ef184368cec9ee65bdfd65baf117811f0a0ce1263ff
  Building wheel for pyrfr (setup.py): started
  Building wheel for pyrfr (setup.py): finished with status 'error'
  Running setup.py clean for pyrfr
  Building wheel for smac (pyproject.toml): started
  Building wheel for smac (pyproject.toml): finished with status 'done'
  Created wheel for smac: filename=smac-1.4.0-py3-none-any.whl size=262387 sha256=8df663b839e1cc4f2d47535af7dfdf4f972c52f4e3f93519de1e2759e5f336b8
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\6e\ba\09\57774b84e13b3e30959e13288552216d31b684f66602cc813e
  Building wheel for pynisher (setup.py): started
  Building wheel for pynisher (setup.py): finished with status 'done'
  Created wheel for pynisher: filename=pynisher-0.6.4-py3-none-any.whl size=7063 sha256=60d63794ee5fe33cea4015472f59cde81f45172bd0b9964fcb08c938378c2bd7
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\6c\70\0a\73bd4c826ba29d3da3be960d3686fa408056f22160c819c272
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492055 sha256=8e4e8fb0281bf5f5e5e581bc0baf8a0ac64ebe3ea6f0c36ad1394c6b644ab712
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\52\2a\fc\520209cfa6448febd490720a0b09036cb367628f7c4e9cc172
Successfully built pycocotools torchviz gym hpbandster gast smac pynisher future
Failed to build pyrfr
Installing collected packages: tokenizers, tensorflow-estimator, sortedcontainers, sentencepiece, safetensors, pycocotools, netifaces, msgpack, lockfile, heapdict, enum-compat, zict, wrapt, Werkzeug, typing-extensions, toolz, tifffile, termcolor, tenacity, tblib, tabulate, Shapely, serpent, scipy, regex, PyWavelets, pyrfr, pynisher, protobuf, pillow, patsy, opt-einsum, opencv-python, networkx, more-itertools, locket, keras-preprocessing, itsdangerous, h5py, grpcio, greenlet, graphviz, google-pasta, gast, future, fsspec, flaky, filelock, emcee, colorlog, cmaes, cloudpickle, atari-py, astor, absl-py, torchserve, torch-model-archiver, torch, scikit-learn, Pyro4, plotly, partd, onnx, keras-applications, imageio, gym, configspace, typeguard, torchviz, torchvision, statsmodels, sqlalchemy, scikit-image, matplotlib, markdown, Mako, lightgbm, huggingface-hub, dask, ale-py, transformers, tensorflow-addons, tensorboard, nltk, imgaug, hpbandster, Flask, distributed, catboost, captum, alembic, tensorflow, smac, optuna, onnx-tf, autoPyTorch
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.6.2
    Uninstalling scipy-1.6.2:
      Successfully uninstalled scipy-1.6.2
  Running setup.py install for pyrfr: started
  Running setup.py install for pyrfr: finished with status 'error'

Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-fd_tz3pt'
  Running command git clone --filter=blob:none --quiet https://github.com/shukon/HpBandSter.git 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-zf013kw8'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      [<setuptools.extension.Extension('pyrfr._regression') at 0x1d11e43b5c8>, <setuptools.extension.Extension('pyrfr._util') at 0x1d11e41d5c8>]
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyrfr
  error: subprocess-exited-with-error

  × Running setup.py install for pyrfr did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      [<setuptools.extension.Extension('pyrfr._regression') at 0x2520508d208>, <setuptools.extension.Extension('pyrfr._util') at 0x25205071208>]
      C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyrfr

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

failed

CondaEnvException: Pip failed


(base) C:\Users\Administrator>

=============================================================


에러가 뜹니다..

그래서 xml에서 문제되는 AutoPytorch 부분을 삭제 후 재설치를 하면.. 설치는 정상적으로 잘됩니다.

conda activate mpytc
python -m ipykernel install --user --name mpytc --display-name "mpytc"

위의 명령어를 사용하여 Jupyter lab 에 만든 mpytc 가상환경을 추가 후.

jupyter lab을 열어서  Python3에서 mpytc로 가상환경으로 진입 후 커널에서 Run All Cell로 실행을 하면...



======================================================================================================


[I 2023-07-11 23:03:52.275 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-07-11 23:03:52.285 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[I 2023-07-11 23:03:52.318 LabApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 2023-07-11 23:03:52.318 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 2023-07-11 23:03:52.320 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-07-11 23:03:52.655 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-07-11 23:03:52.656 ServerApp] Serving notebooks from local directory: C:\Users\Administrator\Desktop\mpytc\Chapter01
[I 2023-07-11 23:03:52.656 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2023-07-11 23:03:52.656 ServerApp] http://localhost:8888/lab?token=24c390dd678d93d9489bd159d9594b5cf827ebb2379129a0
[I 2023-07-11 23:03:52.656 ServerApp]  or http://127.0.0.1:8888/lab?token=24c390dd678d93d9489bd159d9594b5cf827ebb2379129a0
[I 2023-07-11 23:03:52.656 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-07-11 23:03:52.693 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/Administrator/AppData/Roaming/jupyter/runtime/jpserver-12072-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=24c390dd678d93d9489bd159d9594b5cf827ebb2379129a0
     or http://127.0.0.1:8888/lab?token=24c390dd678d93d9489bd159d9594b5cf827ebb2379129a0
[W 2023-07-11 23:03:56.921 LabApp] Could not determine jupyterlab build status without nodejs
[W 2023-07-11 23:04:02.583 ServerApp] Notebook mnist_pytorch.ipynb is not trusted
[I 2023-07-11 23:04:02.785 ServerApp] Kernel started: 91a718f8-8e43-4c12-ae86-ae4f19933ea0
[W 2023-07-11 23:04:06.340 ServerApp] Got events for closed stream None
[I 2023-07-11 23:04:08.144 ServerApp] Kernel restarted: 91a718f8-8e43-4c12-ae86-ae4f19933ea0
[I 2023-07-11 23:04:31.587 ServerApp] Kernel shutdown: 91a718f8-8e43-4c12-ae86-ae4f19933ea0
[I 2023-07-11 23:04:31.828 ServerApp] Kernel started: 8b110273-d260-4a06-afc2-b19788a53d11
[I 2023-07-11 23:04:34.817 ServerApp] Kernel restarted: 8b110273-d260-4a06-afc2-b19788a53d11
[I 2023-07-11 23:04:34.823 ServerApp] Starting buffering for 8b110273-d260-4a06-afc2-b19788a53d11:33e6cfed-95a0-4a06-807e-96a4c542115a
[I 2023-07-11 23:04:34.828 ServerApp] Restoring connection for 8b110273-d260-4a06-afc2-b19788a53d11:33e6cfed-95a0-4a06-807e-96a4c542115a
[I 2023-07-11 23:04:47.001 ServerApp] Kernel shutdown: 8b110273-d260-4a06-afc2-b19788a53d11
[I 2023-07-11 23:04:47.248 ServerApp] Kernel started: bbab99ba-4e27-4b5e-9268-cab00b2a9789
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[I 2023-07-11 23:04:50.246 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[I 2023-07-11 23:04:53.242 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[I 2023-07-11 23:04:56.250 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[I 2023-07-11 23:04:59.242 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[W 2023-07-11 23:05:02.248 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2023-07-11 23:05:02.248 ServerApp] Kernel bbab99ba-4e27-4b5e-9268-cab00b2a9789 died, removing from map.


===========================================================================================================

이런식으로 뜹니다.
수정 부탁드리겠습니다.

**Comment by ychoi-kr** [comment]
보여주신 오류 메시지에 error: command 'swig.exe' failed: None이라는 부분이 있는데, 제가 며칠 전에 테스트했을 때도 똑같은 메시지가 나와서 SWIG을 설치했더니 콘다 가상환경이 잘 만들어졌습니다.

아래 글을 참조해서 SWIG을 설치해 보시기 바랍니다.
https://blog.naver.com/jsf3rd/222285321996

**Comment by ychoi-kr** [comment]
그리고 이번에 environment_gpu.yml을 만들어 올려두었으니, 혹시 CUDA를 사용하신다면 `conda env create -f environment_gpu.yml` 명령으로 설치해 보시기 바랍니다.

**Comment by kakaon1** [comment]
정보 감사합니다. SWIG을 설치해서 AutoPytorch 부분은 해결했는데..

Jupyter lab 에서 mpytc 지정해서  돌렸더니..

Jupyter lab cmd 창에

ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
[I 2023-07-12 11:27:15.359 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    import jupyter_client
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\Anaconda3\envs\mpytc\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (

위와같은 문구가 나오네요..

그리고 2장의 다운로드 부분에..

http://msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip 주소가 안되네요...

두가지 확인 요청드릴게요.
![제목 없음](https://github.com/wikibook/mpytc/assets/93734094/2921e447-689d-46db-b8d5-9f1b17f2ac1f)

**Comment by ychoi-kr** [comment]
#2, #3 이슈를 새로 만들었습니다.
